name: angular_generator
description: Angular generator
version: 0.2.0
homepage: https://www.example.com
author: Naoto Higuchi <ntaoo.g@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.0.0
  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0

executables:
  ngg: main
